/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model.impl;

import com.liferay.lms.model.Competence;
import com.liferay.lms.model.CompetenceModel;
import com.liferay.lms.model.CompetenceSoap;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the Competence service. Represents a row in the &quot;Lms_Competence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.lms.model.CompetenceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompetenceImpl}.
 * </p>
 *
 * @author TLS
 * @see CompetenceImpl
 * @see com.liferay.lms.model.Competence
 * @see com.liferay.lms.model.CompetenceModel
 * @generated
 */
public class CompetenceModelImpl extends BaseModelImpl<Competence>
	implements CompetenceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a competence model instance should use the {@link com.liferay.lms.model.Competence} interface instead.
	 */
	public static final String TABLE_NAME = "Lms_Competence";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "competenceId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "page", Types.VARCHAR },
			{ "generateCertificate", Types.BOOLEAN },
			{ "diplomaTemplate", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Lms_Competence (uuid_ VARCHAR(75) null,competenceId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title STRING null,description STRING null,page VARCHAR(75) null,generateCertificate BOOLEAN,diplomaTemplate STRING null)";
	public static final String TABLE_SQL_DROP = "drop table Lms_Competence";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.lms.model.Competence"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.lms.model.Competence"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.lms.model.Competence"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Competence toModel(CompetenceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Competence model = new CompetenceImpl();

		model.setUuid(soapModel.getUuid());
		model.setCompetenceId(soapModel.getCompetenceId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setPage(soapModel.getPage());
		model.setGenerateCertificate(soapModel.getGenerateCertificate());
		model.setDiplomaTemplate(soapModel.getDiplomaTemplate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Competence> toModels(CompetenceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Competence> models = new ArrayList<Competence>(soapModels.length);

		for (CompetenceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.lms.model.Competence"));

	public CompetenceModelImpl() {
	}

	public long getPrimaryKey() {
		return _competenceId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCompetenceId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_competenceId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Competence.class;
	}

	public String getModelClassName() {
		return Competence.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("competenceId", getCompetenceId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("title", getTitle());
		attributes.put("description", getDescription());
		attributes.put("page", getPage());
		attributes.put("generateCertificate", getGenerateCertificate());
		attributes.put("diplomaTemplate", getDiplomaTemplate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long competenceId = (Long)attributes.get("competenceId");

		if (competenceId != null) {
			setCompetenceId(competenceId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String page = (String)attributes.get("page");

		if (page != null) {
			setPage(page);
		}

		Boolean generateCertificate = (Boolean)attributes.get(
				"generateCertificate");

		if (generateCertificate != null) {
			setGenerateCertificate(generateCertificate);
		}

		String diplomaTemplate = (String)attributes.get("diplomaTemplate");

		if (diplomaTemplate != null) {
			setDiplomaTemplate(diplomaTemplate);
		}
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	public long getCompetenceId() {
		return _competenceId;
	}

	public void setCompetenceId(long competenceId) {
		_competenceId = competenceId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_status = status;
	}

	public long getStatusByUserId() {
		return _statusByUserId;
	}

	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	public Date getStatusDate() {
		return _statusDate;
	}

	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getTitle(), languageId,
			useDefault);
	}

	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	public void setTitle(String title) {
		_title = title;
	}

	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getDefault());
	}

	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(LocalizationUtil.updateLocalization(getTitle(), "Title",
					title, languageId, defaultLanguageId));
		}
		else {
			setTitle(LocalizationUtil.removeLocalization(getTitle(), "Title",
					languageId));
		}
	}

	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getDefault());
	}

	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale) {
		if (titleMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String title = titleMap.get(locale);

			setTitle(title, locale, defaultLocale);
		}
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDescription(), languageId,
			useDefault);
	}

	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	public void setDescription(String description) {
		_description = description;
	}

	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getDefault());
	}

	public void setDescription(String description, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getDefault());
	}

	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale) {
		if (descriptionMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String description = descriptionMap.get(locale);

			setDescription(description, locale, defaultLocale);
		}
	}

	public String getPage() {
		if (_page == null) {
			return StringPool.BLANK;
		}
		else {
			return _page;
		}
	}

	public void setPage(String page) {
		_page = page;
	}

	public boolean getGenerateCertificate() {
		return _generateCertificate;
	}

	public boolean isGenerateCertificate() {
		return _generateCertificate;
	}

	public void setGenerateCertificate(boolean generateCertificate) {
		_generateCertificate = generateCertificate;
	}

	public String getDiplomaTemplate() {
		if (_diplomaTemplate == null) {
			return StringPool.BLANK;
		}
		else {
			return _diplomaTemplate;
		}
	}

	public String getDiplomaTemplate(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDiplomaTemplate(languageId);
	}

	public String getDiplomaTemplate(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDiplomaTemplate(languageId, useDefault);
	}

	public String getDiplomaTemplate(String languageId) {
		return LocalizationUtil.getLocalization(getDiplomaTemplate(), languageId);
	}

	public String getDiplomaTemplate(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getDiplomaTemplate(),
			languageId, useDefault);
	}

	public String getDiplomaTemplateCurrentLanguageId() {
		return _diplomaTemplateCurrentLanguageId;
	}

	@JSON
	public String getDiplomaTemplateCurrentValue() {
		Locale locale = getLocale(_diplomaTemplateCurrentLanguageId);

		return getDiplomaTemplate(locale);
	}

	public Map<Locale, String> getDiplomaTemplateMap() {
		return LocalizationUtil.getLocalizationMap(getDiplomaTemplate());
	}

	public void setDiplomaTemplate(String diplomaTemplate) {
		_diplomaTemplate = diplomaTemplate;
	}

	public void setDiplomaTemplate(String diplomaTemplate, Locale locale) {
		setDiplomaTemplate(diplomaTemplate, locale, LocaleUtil.getDefault());
	}

	public void setDiplomaTemplate(String diplomaTemplate, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(diplomaTemplate)) {
			setDiplomaTemplate(LocalizationUtil.updateLocalization(
					getDiplomaTemplate(), "DiplomaTemplate", diplomaTemplate,
					languageId, defaultLanguageId));
		}
		else {
			setDiplomaTemplate(LocalizationUtil.removeLocalization(
					getDiplomaTemplate(), "DiplomaTemplate", languageId));
		}
	}

	public void setDiplomaTemplateCurrentLanguageId(String languageId) {
		_diplomaTemplateCurrentLanguageId = languageId;
	}

	public void setDiplomaTemplateMap(Map<Locale, String> diplomaTemplateMap) {
		setDiplomaTemplateMap(diplomaTemplateMap, LocaleUtil.getDefault());
	}

	public void setDiplomaTemplateMap(Map<Locale, String> diplomaTemplateMap,
		Locale defaultLocale) {
		if (diplomaTemplateMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String diplomaTemplate = diplomaTemplateMap.get(locale);

			setDiplomaTemplate(diplomaTemplate, locale, defaultLocale);
		}
	}

	/**
	 * @deprecated {@link #isApproved}
	 */
	public boolean getApproved() {
		return isApproved();
	}

	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isDraft() {
		if ((getStatus() == WorkflowConstants.STATUS_DRAFT) ||
				(getStatus() == WorkflowConstants.STATUS_DRAFT_FROM_APPROVED)) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Competence.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		setTitle(getTitle(defaultImportLocale), defaultImportLocale,
			defaultImportLocale);
		setDescription(getDescription(defaultImportLocale),
			defaultImportLocale, defaultImportLocale);
		setDiplomaTemplate(getDiplomaTemplate(defaultImportLocale),
			defaultImportLocale, defaultImportLocale);
	}

	@Override
	public Competence toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Competence)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CompetenceImpl competenceImpl = new CompetenceImpl();

		competenceImpl.setUuid(getUuid());
		competenceImpl.setCompetenceId(getCompetenceId());
		competenceImpl.setCompanyId(getCompanyId());
		competenceImpl.setGroupId(getGroupId());
		competenceImpl.setUserId(getUserId());
		competenceImpl.setStatus(getStatus());
		competenceImpl.setStatusByUserId(getStatusByUserId());
		competenceImpl.setStatusByUserName(getStatusByUserName());
		competenceImpl.setStatusDate(getStatusDate());
		competenceImpl.setTitle(getTitle());
		competenceImpl.setDescription(getDescription());
		competenceImpl.setPage(getPage());
		competenceImpl.setGenerateCertificate(getGenerateCertificate());
		competenceImpl.setDiplomaTemplate(getDiplomaTemplate());

		competenceImpl.resetOriginalValues();

		return competenceImpl;
	}

	public int compareTo(Competence competence) {
		long primaryKey = competence.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Competence competence = null;

		try {
			competence = (Competence)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = competence.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CompetenceModelImpl competenceModelImpl = this;

		competenceModelImpl._originalUuid = competenceModelImpl._uuid;

		competenceModelImpl._originalCompanyId = competenceModelImpl._companyId;

		competenceModelImpl._setOriginalCompanyId = false;

		competenceModelImpl._originalGroupId = competenceModelImpl._groupId;

		competenceModelImpl._setOriginalGroupId = false;

		competenceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Competence> toCacheModel() {
		CompetenceCacheModel competenceCacheModel = new CompetenceCacheModel();

		competenceCacheModel.uuid = getUuid();

		String uuid = competenceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			competenceCacheModel.uuid = null;
		}

		competenceCacheModel.competenceId = getCompetenceId();

		competenceCacheModel.companyId = getCompanyId();

		competenceCacheModel.groupId = getGroupId();

		competenceCacheModel.userId = getUserId();

		competenceCacheModel.status = getStatus();

		competenceCacheModel.statusByUserId = getStatusByUserId();

		competenceCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = competenceCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			competenceCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			competenceCacheModel.statusDate = statusDate.getTime();
		}
		else {
			competenceCacheModel.statusDate = Long.MIN_VALUE;
		}

		competenceCacheModel.title = getTitle();

		String title = competenceCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			competenceCacheModel.title = null;
		}

		competenceCacheModel.description = getDescription();

		String description = competenceCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			competenceCacheModel.description = null;
		}

		competenceCacheModel.page = getPage();

		String page = competenceCacheModel.page;

		if ((page != null) && (page.length() == 0)) {
			competenceCacheModel.page = null;
		}

		competenceCacheModel.generateCertificate = getGenerateCertificate();

		competenceCacheModel.diplomaTemplate = getDiplomaTemplate();

		String diplomaTemplate = competenceCacheModel.diplomaTemplate;

		if ((diplomaTemplate != null) && (diplomaTemplate.length() == 0)) {
			competenceCacheModel.diplomaTemplate = null;
		}

		return competenceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", competenceId=");
		sb.append(getCompetenceId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", page=");
		sb.append(getPage());
		sb.append(", generateCertificate=");
		sb.append(getGenerateCertificate());
		sb.append(", diplomaTemplate=");
		sb.append(getDiplomaTemplate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.lms.model.Competence");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>competenceId</column-name><column-value><![CDATA[");
		sb.append(getCompetenceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>page</column-name><column-value><![CDATA[");
		sb.append(getPage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>generateCertificate</column-name><column-value><![CDATA[");
		sb.append(getGenerateCertificate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diplomaTemplate</column-name><column-value><![CDATA[");
		sb.append(getDiplomaTemplate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Competence.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Competence.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _competenceId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _page;
	private boolean _generateCertificate;
	private String _diplomaTemplate;
	private String _diplomaTemplateCurrentLanguageId;
	private long _columnBitmask;
	private Competence _escapedModelProxy;
}