/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model.impl;

import com.liferay.lms.model.CourseTypeTemplate;
import com.liferay.lms.model.CourseTypeTemplateModel;
import com.liferay.lms.model.CourseTypeTemplateSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CourseTypeTemplate service. Represents a row in the &quot;Lms_CourseTypeTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.lms.model.CourseTypeTemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseTypeTemplateImpl}.
 * </p>
 *
 * @author TLS
 * @see CourseTypeTemplateImpl
 * @see com.liferay.lms.model.CourseTypeTemplate
 * @see com.liferay.lms.model.CourseTypeTemplateModel
 * @generated
 */
public class CourseTypeTemplateModelImpl extends BaseModelImpl<CourseTypeTemplate>
	implements CourseTypeTemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course type template model instance should use the {@link com.liferay.lms.model.CourseTypeTemplate} interface instead.
	 */
	public static final String TABLE_NAME = "Lms_CourseTypeTemplate";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courseTypeTemplateId", Types.BIGINT },
			{ "courseTypeId", Types.BIGINT },
			{ "templateId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Lms_CourseTypeTemplate (courseTypeTemplateId LONG not null primary key,courseTypeId LONG,templateId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Lms_CourseTypeTemplate";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.lms.model.CourseTypeTemplate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.lms.model.CourseTypeTemplate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.lms.model.CourseTypeTemplate"),
			true);
	public static long COURSETYPEID_COLUMN_BITMASK = 1L;
	public static long COURSETYPETEMPLATEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CourseTypeTemplate toModel(CourseTypeTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CourseTypeTemplate model = new CourseTypeTemplateImpl();

		model.setCourseTypeTemplateId(soapModel.getCourseTypeTemplateId());
		model.setCourseTypeId(soapModel.getCourseTypeId());
		model.setTemplateId(soapModel.getTemplateId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CourseTypeTemplate> toModels(
		CourseTypeTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CourseTypeTemplate> models = new ArrayList<CourseTypeTemplate>(soapModels.length);

		for (CourseTypeTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.lms.model.CourseTypeTemplate"));

	public CourseTypeTemplateModelImpl() {
	}

	public long getPrimaryKey() {
		return _courseTypeTemplateId;
	}

	public void setPrimaryKey(long primaryKey) {
		setCourseTypeTemplateId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_courseTypeTemplateId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return CourseTypeTemplate.class;
	}

	public String getModelClassName() {
		return CourseTypeTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("courseTypeTemplateId", getCourseTypeTemplateId());
		attributes.put("courseTypeId", getCourseTypeId());
		attributes.put("templateId", getTemplateId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long courseTypeTemplateId = (Long)attributes.get("courseTypeTemplateId");

		if (courseTypeTemplateId != null) {
			setCourseTypeTemplateId(courseTypeTemplateId);
		}

		Long courseTypeId = (Long)attributes.get("courseTypeId");

		if (courseTypeId != null) {
			setCourseTypeId(courseTypeId);
		}

		Long templateId = (Long)attributes.get("templateId");

		if (templateId != null) {
			setTemplateId(templateId);
		}
	}

	public long getCourseTypeTemplateId() {
		return _courseTypeTemplateId;
	}

	public void setCourseTypeTemplateId(long courseTypeTemplateId) {
		_columnBitmask |= COURSETYPETEMPLATEID_COLUMN_BITMASK;

		if (!_setOriginalCourseTypeTemplateId) {
			_setOriginalCourseTypeTemplateId = true;

			_originalCourseTypeTemplateId = _courseTypeTemplateId;
		}

		_courseTypeTemplateId = courseTypeTemplateId;
	}

	public long getOriginalCourseTypeTemplateId() {
		return _originalCourseTypeTemplateId;
	}

	public long getCourseTypeId() {
		return _courseTypeId;
	}

	public void setCourseTypeId(long courseTypeId) {
		_columnBitmask |= COURSETYPEID_COLUMN_BITMASK;

		if (!_setOriginalCourseTypeId) {
			_setOriginalCourseTypeId = true;

			_originalCourseTypeId = _courseTypeId;
		}

		_courseTypeId = courseTypeId;
	}

	public long getOriginalCourseTypeId() {
		return _originalCourseTypeId;
	}

	public long getTemplateId() {
		return _templateId;
	}

	public void setTemplateId(long templateId) {
		_templateId = templateId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CourseTypeTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CourseTypeTemplate toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (CourseTypeTemplate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		CourseTypeTemplateImpl courseTypeTemplateImpl = new CourseTypeTemplateImpl();

		courseTypeTemplateImpl.setCourseTypeTemplateId(getCourseTypeTemplateId());
		courseTypeTemplateImpl.setCourseTypeId(getCourseTypeId());
		courseTypeTemplateImpl.setTemplateId(getTemplateId());

		courseTypeTemplateImpl.resetOriginalValues();

		return courseTypeTemplateImpl;
	}

	public int compareTo(CourseTypeTemplate courseTypeTemplate) {
		long primaryKey = courseTypeTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		CourseTypeTemplate courseTypeTemplate = null;

		try {
			courseTypeTemplate = (CourseTypeTemplate)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = courseTypeTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CourseTypeTemplateModelImpl courseTypeTemplateModelImpl = this;

		courseTypeTemplateModelImpl._originalCourseTypeTemplateId = courseTypeTemplateModelImpl._courseTypeTemplateId;

		courseTypeTemplateModelImpl._setOriginalCourseTypeTemplateId = false;

		courseTypeTemplateModelImpl._originalCourseTypeId = courseTypeTemplateModelImpl._courseTypeId;

		courseTypeTemplateModelImpl._setOriginalCourseTypeId = false;

		courseTypeTemplateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseTypeTemplate> toCacheModel() {
		CourseTypeTemplateCacheModel courseTypeTemplateCacheModel = new CourseTypeTemplateCacheModel();

		courseTypeTemplateCacheModel.courseTypeTemplateId = getCourseTypeTemplateId();

		courseTypeTemplateCacheModel.courseTypeId = getCourseTypeId();

		courseTypeTemplateCacheModel.templateId = getTemplateId();

		return courseTypeTemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{courseTypeTemplateId=");
		sb.append(getCourseTypeTemplateId());
		sb.append(", courseTypeId=");
		sb.append(getCourseTypeId());
		sb.append(", templateId=");
		sb.append(getTemplateId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.lms.model.CourseTypeTemplate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courseTypeTemplateId</column-name><column-value><![CDATA[");
		sb.append(getCourseTypeTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseTypeId</column-name><column-value><![CDATA[");
		sb.append(getCourseTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templateId</column-name><column-value><![CDATA[");
		sb.append(getTemplateId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CourseTypeTemplate.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			CourseTypeTemplate.class
		};
	private long _courseTypeTemplateId;
	private long _originalCourseTypeTemplateId;
	private boolean _setOriginalCourseTypeTemplateId;
	private long _courseTypeId;
	private long _originalCourseTypeId;
	private boolean _setOriginalCourseTypeId;
	private long _templateId;
	private long _columnBitmask;
	private CourseTypeTemplate _escapedModelProxy;
}