/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model.impl;

import com.liferay.lms.model.P2pActivityCorrections;
import com.liferay.lms.model.P2pActivityCorrectionsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the P2pActivityCorrections service. Represents a row in the &quot;Lms_P2pActivityCorrections&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.lms.model.P2pActivityCorrectionsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link P2pActivityCorrectionsImpl}.
 * </p>
 *
 * @author TLS
 * @see P2pActivityCorrectionsImpl
 * @see com.liferay.lms.model.P2pActivityCorrections
 * @see com.liferay.lms.model.P2pActivityCorrectionsModel
 * @generated
 */
public class P2pActivityCorrectionsModelImpl extends BaseModelImpl<P2pActivityCorrections>
	implements P2pActivityCorrectionsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p2p activity corrections model instance should use the {@link com.liferay.lms.model.P2pActivityCorrections} interface instead.
	 */
	public static final String TABLE_NAME = "Lms_P2pActivityCorrections";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "p2pActivityCorrectionsId", Types.BIGINT },
			{ "p2pActivityId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "actId", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "date_", Types.TIMESTAMP },
			{ "fileEntryId", Types.BIGINT },
			{ "result", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Lms_P2pActivityCorrections (uuid_ VARCHAR(75) null,p2pActivityCorrectionsId LONG not null primary key,p2pActivityId LONG,userId LONG,actId LONG,description TEXT null,date_ DATE null,fileEntryId LONG,result LONG)";
	public static final String TABLE_SQL_DROP = "drop table Lms_P2pActivityCorrections";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.lms.model.P2pActivityCorrections"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.lms.model.P2pActivityCorrections"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.lms.model.P2pActivityCorrections"),
			true);
	public static long ACTID_COLUMN_BITMASK = 1L;
	public static long P2PACTIVITYID_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;
	public static long UUID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.lms.model.P2pActivityCorrections"));

	public P2pActivityCorrectionsModelImpl() {
	}

	public long getPrimaryKey() {
		return _p2pActivityCorrectionsId;
	}

	public void setPrimaryKey(long primaryKey) {
		setP2pActivityCorrectionsId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_p2pActivityCorrectionsId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return P2pActivityCorrections.class;
	}

	public String getModelClassName() {
		return P2pActivityCorrections.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("p2pActivityCorrectionsId", getP2pActivityCorrectionsId());
		attributes.put("p2pActivityId", getP2pActivityId());
		attributes.put("userId", getUserId());
		attributes.put("actId", getActId());
		attributes.put("description", getDescription());
		attributes.put("date", getDate());
		attributes.put("fileEntryId", getFileEntryId());
		attributes.put("result", getResult());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long p2pActivityCorrectionsId = (Long)attributes.get(
				"p2pActivityCorrectionsId");

		if (p2pActivityCorrectionsId != null) {
			setP2pActivityCorrectionsId(p2pActivityCorrectionsId);
		}

		Long p2pActivityId = (Long)attributes.get("p2pActivityId");

		if (p2pActivityId != null) {
			setP2pActivityId(p2pActivityId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long actId = (Long)attributes.get("actId");

		if (actId != null) {
			setActId(actId);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Long fileEntryId = (Long)attributes.get("fileEntryId");

		if (fileEntryId != null) {
			setFileEntryId(fileEntryId);
		}

		Long result = (Long)attributes.get("result");

		if (result != null) {
			setResult(result);
		}
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	public long getP2pActivityCorrectionsId() {
		return _p2pActivityCorrectionsId;
	}

	public void setP2pActivityCorrectionsId(long p2pActivityCorrectionsId) {
		_p2pActivityCorrectionsId = p2pActivityCorrectionsId;
	}

	public long getP2pActivityId() {
		return _p2pActivityId;
	}

	public void setP2pActivityId(long p2pActivityId) {
		_columnBitmask |= P2PACTIVITYID_COLUMN_BITMASK;

		if (!_setOriginalP2pActivityId) {
			_setOriginalP2pActivityId = true;

			_originalP2pActivityId = _p2pActivityId;
		}

		_p2pActivityId = p2pActivityId;
	}

	public long getOriginalP2pActivityId() {
		return _originalP2pActivityId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public long getActId() {
		return _actId;
	}

	public void setActId(long actId) {
		_columnBitmask |= ACTID_COLUMN_BITMASK;

		if (!_setOriginalActId) {
			_setOriginalActId = true;

			_originalActId = _actId;
		}

		_actId = actId;
	}

	public long getOriginalActId() {
		return _originalActId;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public Date getDate() {
		return _date;
	}

	public void setDate(Date date) {
		_date = date;
	}

	public long getFileEntryId() {
		return _fileEntryId;
	}

	public void setFileEntryId(long fileEntryId) {
		_fileEntryId = fileEntryId;
	}

	public long getResult() {
		return _result;
	}

	public void setResult(long result) {
		_result = result;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			P2pActivityCorrections.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public P2pActivityCorrections toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (P2pActivityCorrections)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		P2pActivityCorrectionsImpl p2pActivityCorrectionsImpl = new P2pActivityCorrectionsImpl();

		p2pActivityCorrectionsImpl.setUuid(getUuid());
		p2pActivityCorrectionsImpl.setP2pActivityCorrectionsId(getP2pActivityCorrectionsId());
		p2pActivityCorrectionsImpl.setP2pActivityId(getP2pActivityId());
		p2pActivityCorrectionsImpl.setUserId(getUserId());
		p2pActivityCorrectionsImpl.setActId(getActId());
		p2pActivityCorrectionsImpl.setDescription(getDescription());
		p2pActivityCorrectionsImpl.setDate(getDate());
		p2pActivityCorrectionsImpl.setFileEntryId(getFileEntryId());
		p2pActivityCorrectionsImpl.setResult(getResult());

		p2pActivityCorrectionsImpl.resetOriginalValues();

		return p2pActivityCorrectionsImpl;
	}

	public int compareTo(P2pActivityCorrections p2pActivityCorrections) {
		long primaryKey = p2pActivityCorrections.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		P2pActivityCorrections p2pActivityCorrections = null;

		try {
			p2pActivityCorrections = (P2pActivityCorrections)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = p2pActivityCorrections.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		P2pActivityCorrectionsModelImpl p2pActivityCorrectionsModelImpl = this;

		p2pActivityCorrectionsModelImpl._originalUuid = p2pActivityCorrectionsModelImpl._uuid;

		p2pActivityCorrectionsModelImpl._originalP2pActivityId = p2pActivityCorrectionsModelImpl._p2pActivityId;

		p2pActivityCorrectionsModelImpl._setOriginalP2pActivityId = false;

		p2pActivityCorrectionsModelImpl._originalUserId = p2pActivityCorrectionsModelImpl._userId;

		p2pActivityCorrectionsModelImpl._setOriginalUserId = false;

		p2pActivityCorrectionsModelImpl._originalActId = p2pActivityCorrectionsModelImpl._actId;

		p2pActivityCorrectionsModelImpl._setOriginalActId = false;

		p2pActivityCorrectionsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<P2pActivityCorrections> toCacheModel() {
		P2pActivityCorrectionsCacheModel p2pActivityCorrectionsCacheModel = new P2pActivityCorrectionsCacheModel();

		p2pActivityCorrectionsCacheModel.uuid = getUuid();

		String uuid = p2pActivityCorrectionsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			p2pActivityCorrectionsCacheModel.uuid = null;
		}

		p2pActivityCorrectionsCacheModel.p2pActivityCorrectionsId = getP2pActivityCorrectionsId();

		p2pActivityCorrectionsCacheModel.p2pActivityId = getP2pActivityId();

		p2pActivityCorrectionsCacheModel.userId = getUserId();

		p2pActivityCorrectionsCacheModel.actId = getActId();

		p2pActivityCorrectionsCacheModel.description = getDescription();

		String description = p2pActivityCorrectionsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			p2pActivityCorrectionsCacheModel.description = null;
		}

		Date date = getDate();

		if (date != null) {
			p2pActivityCorrectionsCacheModel.date = date.getTime();
		}
		else {
			p2pActivityCorrectionsCacheModel.date = Long.MIN_VALUE;
		}

		p2pActivityCorrectionsCacheModel.fileEntryId = getFileEntryId();

		p2pActivityCorrectionsCacheModel.result = getResult();

		return p2pActivityCorrectionsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", p2pActivityCorrectionsId=");
		sb.append(getP2pActivityCorrectionsId());
		sb.append(", p2pActivityId=");
		sb.append(getP2pActivityId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", actId=");
		sb.append(getActId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", fileEntryId=");
		sb.append(getFileEntryId());
		sb.append(", result=");
		sb.append(getResult());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.lms.model.P2pActivityCorrections");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>p2pActivityCorrectionsId</column-name><column-value><![CDATA[");
		sb.append(getP2pActivityCorrectionsId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>p2pActivityId</column-name><column-value><![CDATA[");
		sb.append(getP2pActivityId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actId</column-name><column-value><![CDATA[");
		sb.append(getActId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileEntryId</column-name><column-value><![CDATA[");
		sb.append(getFileEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>result</column-name><column-value><![CDATA[");
		sb.append(getResult());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = P2pActivityCorrections.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			P2pActivityCorrections.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _p2pActivityCorrectionsId;
	private long _p2pActivityId;
	private long _originalP2pActivityId;
	private boolean _setOriginalP2pActivityId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _actId;
	private long _originalActId;
	private boolean _setOriginalActId;
	private String _description;
	private Date _date;
	private long _fileEntryId;
	private long _result;
	private long _columnBitmask;
	private P2pActivityCorrections _escapedModelProxy;
}