/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model.impl;

import com.liferay.lms.model.P2pActivity;
import com.liferay.lms.service.P2pActivityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the P2pActivity service. Represents a row in the &quot;Lms_P2pActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link P2pActivityImpl}.
 * </p>
 *
 * @author TLS
 * @see P2pActivityImpl
 * @see com.liferay.lms.model.P2pActivity
 * @generated
 */
public abstract class P2pActivityBaseImpl extends P2pActivityModelImpl
	implements P2pActivity {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a p2p activity model instance should use the {@link P2pActivity} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			P2pActivityLocalServiceUtil.addP2pActivity(this);
		}
		else {
			P2pActivityLocalServiceUtil.updateP2pActivity(this);
		}
	}
}