/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model.impl;

import com.liferay.lms.model.Schedule;
import com.liferay.lms.model.ScheduleModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Schedule service. Represents a row in the &quot;Lms_Schedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.lms.model.ScheduleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScheduleImpl}.
 * </p>
 *
 * @author TLS
 * @see ScheduleImpl
 * @see com.liferay.lms.model.Schedule
 * @see com.liferay.lms.model.ScheduleModel
 * @generated
 */
public class ScheduleModelImpl extends BaseModelImpl<Schedule>
	implements ScheduleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a schedule model instance should use the {@link com.liferay.lms.model.Schedule} interface instead.
	 */
	public static final String TABLE_NAME = "Lms_Schedule";
	public static final Object[][] TABLE_COLUMNS = {
			{ "secheduleId", Types.BIGINT },
			{ "teamId", Types.BIGINT },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Lms_Schedule (secheduleId LONG not null primary key,teamId LONG,startDate DATE null,endDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Lms_Schedule";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.lms.model.Schedule"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.lms.model.Schedule"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.lms.model.Schedule"),
			true);
	public static long TEAMID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.lms.model.Schedule"));

	public ScheduleModelImpl() {
	}

	public long getPrimaryKey() {
		return _secheduleId;
	}

	public void setPrimaryKey(long primaryKey) {
		setSecheduleId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_secheduleId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Schedule.class;
	}

	public String getModelClassName() {
		return Schedule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("secheduleId", getSecheduleId());
		attributes.put("teamId", getTeamId());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long secheduleId = (Long)attributes.get("secheduleId");

		if (secheduleId != null) {
			setSecheduleId(secheduleId);
		}

		Long teamId = (Long)attributes.get("teamId");

		if (teamId != null) {
			setTeamId(teamId);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}
	}

	public long getSecheduleId() {
		return _secheduleId;
	}

	public void setSecheduleId(long secheduleId) {
		_secheduleId = secheduleId;
	}

	public long getTeamId() {
		return _teamId;
	}

	public void setTeamId(long teamId) {
		_columnBitmask |= TEAMID_COLUMN_BITMASK;

		if (!_setOriginalTeamId) {
			_setOriginalTeamId = true;

			_originalTeamId = _teamId;
		}

		_teamId = teamId;
	}

	public long getOriginalTeamId() {
		return _originalTeamId;
	}

	public Date getStartDate() {
		return _startDate;
	}

	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	public Date getEndDate() {
		return _endDate;
	}

	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Schedule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Schedule toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Schedule)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ScheduleImpl scheduleImpl = new ScheduleImpl();

		scheduleImpl.setSecheduleId(getSecheduleId());
		scheduleImpl.setTeamId(getTeamId());
		scheduleImpl.setStartDate(getStartDate());
		scheduleImpl.setEndDate(getEndDate());

		scheduleImpl.resetOriginalValues();

		return scheduleImpl;
	}

	public int compareTo(Schedule schedule) {
		long primaryKey = schedule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Schedule schedule = null;

		try {
			schedule = (Schedule)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = schedule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ScheduleModelImpl scheduleModelImpl = this;

		scheduleModelImpl._originalTeamId = scheduleModelImpl._teamId;

		scheduleModelImpl._setOriginalTeamId = false;

		scheduleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Schedule> toCacheModel() {
		ScheduleCacheModel scheduleCacheModel = new ScheduleCacheModel();

		scheduleCacheModel.secheduleId = getSecheduleId();

		scheduleCacheModel.teamId = getTeamId();

		Date startDate = getStartDate();

		if (startDate != null) {
			scheduleCacheModel.startDate = startDate.getTime();
		}
		else {
			scheduleCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			scheduleCacheModel.endDate = endDate.getTime();
		}
		else {
			scheduleCacheModel.endDate = Long.MIN_VALUE;
		}

		return scheduleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{secheduleId=");
		sb.append(getSecheduleId());
		sb.append(", teamId=");
		sb.append(getTeamId());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.lms.model.Schedule");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>secheduleId</column-name><column-value><![CDATA[");
		sb.append(getSecheduleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>teamId</column-name><column-value><![CDATA[");
		sb.append(getTeamId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Schedule.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Schedule.class
		};
	private long _secheduleId;
	private long _teamId;
	private long _originalTeamId;
	private boolean _setOriginalTeamId;
	private Date _startDate;
	private Date _endDate;
	private long _columnBitmask;
	private Schedule _escapedModelProxy;
}