/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditEntry service. Represents a row in the &quot;Lms_AuditEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.AuditEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.AuditEntryImpl}.
 * </p>
 *
 * @author TLS
 * @see AuditEntry
 * @see com.liferay.lms.model.impl.AuditEntryImpl
 * @see com.liferay.lms.model.impl.AuditEntryModelImpl
 * @generated
 */
public interface AuditEntryModel extends BaseModel<AuditEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit entry model instance should use the {@link AuditEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this audit entry.
	 *
	 * @return the primary key of this audit entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit entry.
	 *
	 * @param primaryKey the primary key of this audit entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this audit entry.
	 *
	 * @return the audit ID of this audit entry
	 */
	public long getAuditId();

	/**
	 * Sets the audit ID of this audit entry.
	 *
	 * @param auditId the audit ID of this audit entry
	 */
	public void setAuditId(long auditId);

	/**
	 * Returns the audit date of this audit entry.
	 *
	 * @return the audit date of this audit entry
	 */
	public Date getAuditDate();

	/**
	 * Sets the audit date of this audit entry.
	 *
	 * @param auditDate the audit date of this audit entry
	 */
	public void setAuditDate(Date auditDate);

	/**
	 * Returns the company ID of this audit entry.
	 *
	 * @return the company ID of this audit entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit entry.
	 *
	 * @param companyId the company ID of this audit entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this audit entry.
	 *
	 * @return the group ID of this audit entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this audit entry.
	 *
	 * @param groupId the group ID of this audit entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this audit entry.
	 *
	 * @return the user ID of this audit entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audit entry.
	 *
	 * @param userId the user ID of this audit entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit entry.
	 *
	 * @return the user uuid of this audit entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this audit entry.
	 *
	 * @param userUuid the user uuid of this audit entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the classname of this audit entry.
	 *
	 * @return the classname of this audit entry
	 */
	@AutoEscape
	public String getClassname();

	/**
	 * Sets the classname of this audit entry.
	 *
	 * @param classname the classname of this audit entry
	 */
	public void setClassname(String classname);

	/**
	 * Returns the action of this audit entry.
	 *
	 * @return the action of this audit entry
	 */
	@AutoEscape
	public String getAction();

	/**
	 * Sets the action of this audit entry.
	 *
	 * @param action the action of this audit entry
	 */
	public void setAction(String action);

	/**
	 * Returns the extradata of this audit entry.
	 *
	 * @return the extradata of this audit entry
	 */
	@AutoEscape
	public String getExtradata();

	/**
	 * Sets the extradata of this audit entry.
	 *
	 * @param extradata the extradata of this audit entry
	 */
	public void setExtradata(String extradata);

	/**
	 * Returns the class p k of this audit entry.
	 *
	 * @return the class p k of this audit entry
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this audit entry.
	 *
	 * @param classPK the class p k of this audit entry
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the association class p k of this audit entry.
	 *
	 * @return the association class p k of this audit entry
	 */
	public long getAssociationClassPK();

	/**
	 * Sets the association class p k of this audit entry.
	 *
	 * @param associationClassPK the association class p k of this audit entry
	 */
	public void setAssociationClassPK(long associationClassPK);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AuditEntry auditEntry);

	public int hashCode();

	public CacheModel<AuditEntry> toCacheModel();

	public AuditEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}