/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Course service. Represents a row in the &quot;Lms_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.CourseImpl}.
 * </p>
 *
 * @author TLS
 * @see Course
 * @see com.liferay.lms.model.impl.CourseImpl
 * @see com.liferay.lms.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course>, GroupedModel,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course.
	 *
	 * @return the uuid of this course
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this course.
	 *
	 * @param uuid the uuid of this course
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the company ID of this course.
	 *
	 * @return the company ID of this course
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this course.
	 *
	 * @param companyId the company ID of this course
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this course.
	 *
	 * @return the group ID of this course
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this course.
	 *
	 * @param groupId the group ID of this course
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this course.
	 *
	 * @return the user ID of this course
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this course.
	 *
	 * @param userId the user ID of this course
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course.
	 *
	 * @return the user uuid of this course
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course.
	 *
	 * @param userUuid the user uuid of this course
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course.
	 *
	 * @return the user name of this course
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this course.
	 *
	 * @param userName the user name of this course
	 */
	public void setUserName(String userName);

	/**
	 * Returns the group created ID of this course.
	 *
	 * @return the group created ID of this course
	 */
	public long getGroupCreatedId();

	/**
	 * Sets the group created ID of this course.
	 *
	 * @param groupCreatedId the group created ID of this course
	 */
	public void setGroupCreatedId(long groupCreatedId);

	/**
	 * Returns the create date of this course.
	 *
	 * @return the create date of this course
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this course.
	 *
	 * @param createDate the create date of this course
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course.
	 *
	 * @return the modified date of this course
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course.
	 *
	 * @param modifiedDate the modified date of this course
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this course.
	 *
	 * @return the status of this course
	 */
	public int getStatus();

	/**
	 * Sets the status of this course.
	 *
	 * @param status the status of this course
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this course.
	 *
	 * @return the status by user ID of this course
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this course.
	 *
	 * @param statusByUserId the status by user ID of this course
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this course.
	 *
	 * @return the status by user uuid of this course
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this course.
	 *
	 * @param statusByUserUuid the status by user uuid of this course
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this course.
	 *
	 * @return the status by user name of this course
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this course.
	 *
	 * @param statusByUserName the status by user name of this course
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this course.
	 *
	 * @return the status date of this course
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this course.
	 *
	 * @param statusDate the status date of this course
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this course.
	 *
	 * @return the title of this course
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this course. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this course
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this course.
	 *
	 * @return the locales and localized titles of this course
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this course.
	 *
	 * @param title the title of this course
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this course in the language.
	 *
	 * @param title the localized title of this course
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this course in the language, and sets the default locale.
	 *
	 * @param title the localized title of this course
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this course from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this course
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this course from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this course
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this course.
	 *
	 * @return the description of this course
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this course. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this course in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this course in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this course
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this course.
	 *
	 * @return the locales and localized descriptions of this course
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this course.
	 *
	 * @param description the description of this course
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this course in the language.
	 *
	 * @param description the localized description of this course
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this course in the language, and sets the default locale.
	 *
	 * @param description the localized description of this course
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this course from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this course
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this course from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this course
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the friendly u r l of this course.
	 *
	 * @return the friendly u r l of this course
	 */
	@AutoEscape
	public String getFriendlyURL();

	/**
	 * Sets the friendly u r l of this course.
	 *
	 * @param friendlyURL the friendly u r l of this course
	 */
	public void setFriendlyURL(String friendlyURL);

	/**
	 * Returns the start date of this course.
	 *
	 * @return the start date of this course
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this course.
	 *
	 * @param startDate the start date of this course
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this course.
	 *
	 * @return the end date of this course
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this course.
	 *
	 * @param endDate the end date of this course
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the icon of this course.
	 *
	 * @return the icon of this course
	 */
	public long getIcon();

	/**
	 * Sets the icon of this course.
	 *
	 * @param icon the icon of this course
	 */
	public void setIcon(long icon);

	/**
	 * Returns the course eval ID of this course.
	 *
	 * @return the course eval ID of this course
	 */
	public long getCourseEvalId();

	/**
	 * Sets the course eval ID of this course.
	 *
	 * @param CourseEvalId the course eval ID of this course
	 */
	public void setCourseEvalId(long CourseEvalId);

	/**
	 * Returns the course extra data of this course.
	 *
	 * @return the course extra data of this course
	 */
	@AutoEscape
	public String getCourseExtraData();

	/**
	 * Sets the course extra data of this course.
	 *
	 * @param CourseExtraData the course extra data of this course
	 */
	public void setCourseExtraData(String CourseExtraData);

	/**
	 * Returns the closed of this course.
	 *
	 * @return the closed of this course
	 */
	public boolean getClosed();

	/**
	 * Returns <code>true</code> if this course is closed.
	 *
	 * @return <code>true</code> if this course is closed; <code>false</code> otherwise
	 */
	public boolean isClosed();

	/**
	 * Sets whether this course is closed.
	 *
	 * @param closed the closed of this course
	 */
	public void setClosed(boolean closed);

	/**
	 * Returns the maxusers of this course.
	 *
	 * @return the maxusers of this course
	 */
	public long getMaxusers();

	/**
	 * Sets the maxusers of this course.
	 *
	 * @param maxusers the maxusers of this course
	 */
	public void setMaxusers(long maxusers);

	/**
	 * Returns the calification type of this course.
	 *
	 * @return the calification type of this course
	 */
	public long getCalificationType();

	/**
	 * Sets the calification type of this course.
	 *
	 * @param calificationType the calification type of this course
	 */
	public void setCalificationType(long calificationType);

	/**
	 * Returns the welcome of this course.
	 *
	 * @return the welcome of this course
	 */
	public boolean getWelcome();

	/**
	 * Returns <code>true</code> if this course is welcome.
	 *
	 * @return <code>true</code> if this course is welcome; <code>false</code> otherwise
	 */
	public boolean isWelcome();

	/**
	 * Sets whether this course is welcome.
	 *
	 * @param welcome the welcome of this course
	 */
	public void setWelcome(boolean welcome);

	/**
	 * Returns the welcome msg of this course.
	 *
	 * @return the welcome msg of this course
	 */
	@AutoEscape
	public String getWelcomeMsg();

	/**
	 * Sets the welcome msg of this course.
	 *
	 * @param welcomeMsg the welcome msg of this course
	 */
	public void setWelcomeMsg(String welcomeMsg);

	/**
	 * Returns the welcome subject of this course.
	 *
	 * @return the welcome subject of this course
	 */
	@AutoEscape
	public String getWelcomeSubject();

	/**
	 * Sets the welcome subject of this course.
	 *
	 * @param welcomeSubject the welcome subject of this course
	 */
	public void setWelcomeSubject(String welcomeSubject);

	/**
	 * @deprecated Renamed to {@link #isApproved()}
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this course is approved.
	 *
	 * @return <code>true</code> if this course is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this course is denied.
	 *
	 * @return <code>true</code> if this course is denied; <code>false</code> otherwise
	 */
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this course is a draft.
	 *
	 * @return <code>true</code> if this course is a draft; <code>false</code> otherwise
	 */
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this course is expired.
	 *
	 * @return <code>true</code> if this course is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this course is inactive.
	 *
	 * @return <code>true</code> if this course is inactive; <code>false</code> otherwise
	 */
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this course is incomplete.
	 *
	 * @return <code>true</code> if this course is incomplete; <code>false</code> otherwise
	 */
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this course is pending.
	 *
	 * @return <code>true</code> if this course is pending; <code>false</code> otherwise
	 */
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this course is scheduled.
	 *
	 * @return <code>true</code> if this course is scheduled; <code>false</code> otherwise
	 */
	public boolean isScheduled();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	public Object clone();

	public int compareTo(Course course);

	public int hashCode();

	public CacheModel<Course> toCacheModel();

	public Course toEscapedModel();

	public String toString();

	public String toXmlString();
}