/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CourseCompetence service. Represents a row in the &quot;Lms_CourseCompetence&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.CourseCompetenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.CourseCompetenceImpl}.
 * </p>
 *
 * @author TLS
 * @see CourseCompetence
 * @see com.liferay.lms.model.impl.CourseCompetenceImpl
 * @see com.liferay.lms.model.impl.CourseCompetenceModelImpl
 * @generated
 */
public interface CourseCompetenceModel extends BaseModel<CourseCompetence> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course competence model instance should use the {@link CourseCompetence} interface instead.
	 */

	/**
	 * Returns the primary key of this course competence.
	 *
	 * @return the primary key of this course competence
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course competence.
	 *
	 * @param primaryKey the primary key of this course competence
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course competence.
	 *
	 * @return the uuid of this course competence
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this course competence.
	 *
	 * @param uuid the uuid of this course competence
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the courcompetence ID of this course competence.
	 *
	 * @return the courcompetence ID of this course competence
	 */
	public long getCourcompetenceId();

	/**
	 * Sets the courcompetence ID of this course competence.
	 *
	 * @param CourcompetenceId the courcompetence ID of this course competence
	 */
	public void setCourcompetenceId(long CourcompetenceId);

	/**
	 * Returns the course ID of this course competence.
	 *
	 * @return the course ID of this course competence
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course competence.
	 *
	 * @param courseId the course ID of this course competence
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the competence ID of this course competence.
	 *
	 * @return the competence ID of this course competence
	 */
	public long getCompetenceId();

	/**
	 * Sets the competence ID of this course competence.
	 *
	 * @param competenceId the competence ID of this course competence
	 */
	public void setCompetenceId(long competenceId);

	/**
	 * Returns the condition of this course competence.
	 *
	 * @return the condition of this course competence
	 */
	public boolean getCondition();

	/**
	 * Returns <code>true</code> if this course competence is condition.
	 *
	 * @return <code>true</code> if this course competence is condition; <code>false</code> otherwise
	 */
	public boolean isCondition();

	/**
	 * Sets whether this course competence is condition.
	 *
	 * @param condition the condition of this course competence
	 */
	public void setCondition(boolean condition);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CourseCompetence courseCompetence);

	public int hashCode();

	public CacheModel<CourseCompetence> toCacheModel();

	public CourseCompetence toEscapedModel();

	public String toString();

	public String toXmlString();
}