/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ModuleResult service. Represents a row in the &quot;Lms_ModuleResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.ModuleResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.ModuleResultImpl}.
 * </p>
 *
 * @author TLS
 * @see ModuleResult
 * @see com.liferay.lms.model.impl.ModuleResultImpl
 * @see com.liferay.lms.model.impl.ModuleResultModelImpl
 * @generated
 */
public interface ModuleResultModel extends BaseModel<ModuleResult> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a module result model instance should use the {@link ModuleResult} interface instead.
	 */

	/**
	 * Returns the primary key of this module result.
	 *
	 * @return the primary key of this module result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this module result.
	 *
	 * @param primaryKey the primary key of this module result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the module ID of this module result.
	 *
	 * @return the module ID of this module result
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this module result.
	 *
	 * @param moduleId the module ID of this module result
	 */
	public void setModuleId(long moduleId);

	/**
	 * Returns the result of this module result.
	 *
	 * @return the result of this module result
	 */
	public long getResult();

	/**
	 * Sets the result of this module result.
	 *
	 * @param result the result of this module result
	 */
	public void setResult(long result);

	/**
	 * Returns the comments of this module result.
	 *
	 * @return the comments of this module result
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this module result.
	 *
	 * @param comments the comments of this module result
	 */
	public void setComments(String comments);

	/**
	 * Returns the user ID of this module result.
	 *
	 * @return the user ID of this module result
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this module result.
	 *
	 * @param userId the user ID of this module result
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this module result.
	 *
	 * @return the user uuid of this module result
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this module result.
	 *
	 * @param userUuid the user uuid of this module result
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the start date of this module result.
	 *
	 * @return the start date of this module result
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this module result.
	 *
	 * @param startDate the start date of this module result
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the passed of this module result.
	 *
	 * @return the passed of this module result
	 */
	public boolean getPassed();

	/**
	 * Returns <code>true</code> if this module result is passed.
	 *
	 * @return <code>true</code> if this module result is passed; <code>false</code> otherwise
	 */
	public boolean isPassed();

	/**
	 * Sets whether this module result is passed.
	 *
	 * @param passed the passed of this module result
	 */
	public void setPassed(boolean passed);

	/**
	 * Returns the mr ID of this module result.
	 *
	 * @return the mr ID of this module result
	 */
	public long getMrId();

	/**
	 * Sets the mr ID of this module result.
	 *
	 * @param mrId the mr ID of this module result
	 */
	public void setMrId(long mrId);

	/**
	 * Returns the passed date of this module result.
	 *
	 * @return the passed date of this module result
	 */
	public Date getPassedDate();

	/**
	 * Sets the passed date of this module result.
	 *
	 * @param passedDate the passed date of this module result
	 */
	public void setPassedDate(Date passedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ModuleResult moduleResult);

	public int hashCode();

	public CacheModel<ModuleResult> toCacheModel();

	public ModuleResult toEscapedModel();

	public String toString();

	public String toXmlString();
}