/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SCORMContent service. Represents a row in the &quot;Lms_SCORMContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.SCORMContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.SCORMContentImpl}.
 * </p>
 *
 * @author TLS
 * @see SCORMContent
 * @see com.liferay.lms.model.impl.SCORMContentImpl
 * @see com.liferay.lms.model.impl.SCORMContentModelImpl
 * @generated
 */
public interface SCORMContentModel extends BaseModel<SCORMContent>,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a s c o r m content model instance should use the {@link SCORMContent} interface instead.
	 */

	/**
	 * Returns the primary key of this s c o r m content.
	 *
	 * @return the primary key of this s c o r m content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this s c o r m content.
	 *
	 * @param primaryKey the primary key of this s c o r m content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this s c o r m content.
	 *
	 * @return the uuid of this s c o r m content
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this s c o r m content.
	 *
	 * @param uuid the uuid of this s c o r m content
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the scorm ID of this s c o r m content.
	 *
	 * @return the scorm ID of this s c o r m content
	 */
	public long getScormId();

	/**
	 * Sets the scorm ID of this s c o r m content.
	 *
	 * @param scormId the scorm ID of this s c o r m content
	 */
	public void setScormId(long scormId);

	/**
	 * Returns the company ID of this s c o r m content.
	 *
	 * @return the company ID of this s c o r m content
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this s c o r m content.
	 *
	 * @param companyId the company ID of this s c o r m content
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this s c o r m content.
	 *
	 * @return the group ID of this s c o r m content
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this s c o r m content.
	 *
	 * @param groupId the group ID of this s c o r m content
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this s c o r m content.
	 *
	 * @return the user ID of this s c o r m content
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this s c o r m content.
	 *
	 * @param userId the user ID of this s c o r m content
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this s c o r m content.
	 *
	 * @return the user uuid of this s c o r m content
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this s c o r m content.
	 *
	 * @param userUuid the user uuid of this s c o r m content
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the status of this s c o r m content.
	 *
	 * @return the status of this s c o r m content
	 */
	public int getStatus();

	/**
	 * Sets the status of this s c o r m content.
	 *
	 * @param status the status of this s c o r m content
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this s c o r m content.
	 *
	 * @return the status by user ID of this s c o r m content
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this s c o r m content.
	 *
	 * @param statusByUserId the status by user ID of this s c o r m content
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this s c o r m content.
	 *
	 * @return the status by user uuid of this s c o r m content
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this s c o r m content.
	 *
	 * @param statusByUserUuid the status by user uuid of this s c o r m content
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this s c o r m content.
	 *
	 * @return the status by user name of this s c o r m content
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this s c o r m content.
	 *
	 * @param statusByUserName the status by user name of this s c o r m content
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this s c o r m content.
	 *
	 * @return the status date of this s c o r m content
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this s c o r m content.
	 *
	 * @param statusDate the status date of this s c o r m content
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this s c o r m content.
	 *
	 * @return the title of this s c o r m content
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this s c o r m content.
	 *
	 * @param title the title of this s c o r m content
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this s c o r m content.
	 *
	 * @return the description of this s c o r m content
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this s c o r m content.
	 *
	 * @param description the description of this s c o r m content
	 */
	public void setDescription(String description);

	/**
	 * Returns the index of this s c o r m content.
	 *
	 * @return the index of this s c o r m content
	 */
	@AutoEscape
	public String getIndex();

	/**
	 * Sets the index of this s c o r m content.
	 *
	 * @param index the index of this s c o r m content
	 */
	public void setIndex(String index);

	/**
	 * Returns the ciphered of this s c o r m content.
	 *
	 * @return the ciphered of this s c o r m content
	 */
	public boolean getCiphered();

	/**
	 * Returns <code>true</code> if this s c o r m content is ciphered.
	 *
	 * @return <code>true</code> if this s c o r m content is ciphered; <code>false</code> otherwise
	 */
	public boolean isCiphered();

	/**
	 * Sets whether this s c o r m content is ciphered.
	 *
	 * @param ciphered the ciphered of this s c o r m content
	 */
	public void setCiphered(boolean ciphered);

	/**
	 * @deprecated Renamed to {@link #isApproved()}
	 */
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this s c o r m content is approved.
	 *
	 * @return <code>true</code> if this s c o r m content is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this s c o r m content is denied.
	 *
	 * @return <code>true</code> if this s c o r m content is denied; <code>false</code> otherwise
	 */
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this s c o r m content is a draft.
	 *
	 * @return <code>true</code> if this s c o r m content is a draft; <code>false</code> otherwise
	 */
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this s c o r m content is expired.
	 *
	 * @return <code>true</code> if this s c o r m content is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this s c o r m content is inactive.
	 *
	 * @return <code>true</code> if this s c o r m content is inactive; <code>false</code> otherwise
	 */
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this s c o r m content is incomplete.
	 *
	 * @return <code>true</code> if this s c o r m content is incomplete; <code>false</code> otherwise
	 */
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this s c o r m content is pending.
	 *
	 * @return <code>true</code> if this s c o r m content is pending; <code>false</code> otherwise
	 */
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this s c o r m content is scheduled.
	 *
	 * @return <code>true</code> if this s c o r m content is scheduled; <code>false</code> otherwise
	 */
	public boolean isScheduled();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SCORMContent scormContent);

	public int hashCode();

	public CacheModel<SCORMContent> toCacheModel();

	public SCORMContent toEscapedModel();

	public String toString();

	public String toXmlString();
}