/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SurveyResult service. Represents a row in the &quot;Lms_SurveyResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.SurveyResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.SurveyResultImpl}.
 * </p>
 *
 * @author TLS
 * @see SurveyResult
 * @see com.liferay.lms.model.impl.SurveyResultImpl
 * @see com.liferay.lms.model.impl.SurveyResultModelImpl
 * @generated
 */
public interface SurveyResultModel extends BaseModel<SurveyResult> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey result model instance should use the {@link SurveyResult} interface instead.
	 */

	/**
	 * Returns the primary key of this survey result.
	 *
	 * @return the primary key of this survey result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey result.
	 *
	 * @param primaryKey the primary key of this survey result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this survey result.
	 *
	 * @return the uuid of this survey result
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this survey result.
	 *
	 * @param uuid the uuid of this survey result
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the survey result ID of this survey result.
	 *
	 * @return the survey result ID of this survey result
	 */
	public long getSurveyResultId();

	/**
	 * Sets the survey result ID of this survey result.
	 *
	 * @param surveyResultId the survey result ID of this survey result
	 */
	public void setSurveyResultId(long surveyResultId);

	/**
	 * Returns the act ID of this survey result.
	 *
	 * @return the act ID of this survey result
	 */
	public long getActId();

	/**
	 * Sets the act ID of this survey result.
	 *
	 * @param actId the act ID of this survey result
	 */
	public void setActId(long actId);

	/**
	 * Returns the lat ID of this survey result.
	 *
	 * @return the lat ID of this survey result
	 */
	public long getLatId();

	/**
	 * Sets the lat ID of this survey result.
	 *
	 * @param latId the lat ID of this survey result
	 */
	public void setLatId(long latId);

	/**
	 * Returns the question ID of this survey result.
	 *
	 * @return the question ID of this survey result
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this survey result.
	 *
	 * @param questionId the question ID of this survey result
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the answer ID of this survey result.
	 *
	 * @return the answer ID of this survey result
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this survey result.
	 *
	 * @param answerId the answer ID of this survey result
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the user ID of this survey result.
	 *
	 * @return the user ID of this survey result
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this survey result.
	 *
	 * @param userId the user ID of this survey result
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this survey result.
	 *
	 * @return the user uuid of this survey result
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this survey result.
	 *
	 * @param userUuid the user uuid of this survey result
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the free answer of this survey result.
	 *
	 * @return the free answer of this survey result
	 */
	@AutoEscape
	public String getFreeAnswer();

	/**
	 * Sets the free answer of this survey result.
	 *
	 * @param freeAnswer the free answer of this survey result
	 */
	public void setFreeAnswer(String freeAnswer);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SurveyResult surveyResult);

	public int hashCode();

	public CacheModel<SurveyResult> toCacheModel();

	public SurveyResult toEscapedModel();

	public String toString();

	public String toXmlString();
}