/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.lms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TestAnswer service. Represents a row in the &quot;Lms_TestAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.lms.model.impl.TestAnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.lms.model.impl.TestAnswerImpl}.
 * </p>
 *
 * @author TLS
 * @see TestAnswer
 * @see com.liferay.lms.model.impl.TestAnswerImpl
 * @see com.liferay.lms.model.impl.TestAnswerModelImpl
 * @generated
 */
public interface TestAnswerModel extends BaseModel<TestAnswer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a test answer model instance should use the {@link TestAnswer} interface instead.
	 */

	/**
	 * Returns the primary key of this test answer.
	 *
	 * @return the primary key of this test answer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this test answer.
	 *
	 * @param primaryKey the primary key of this test answer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this test answer.
	 *
	 * @return the uuid of this test answer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this test answer.
	 *
	 * @param uuid the uuid of this test answer
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the answer ID of this test answer.
	 *
	 * @return the answer ID of this test answer
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this test answer.
	 *
	 * @param answerId the answer ID of this test answer
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the question ID of this test answer.
	 *
	 * @return the question ID of this test answer
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this test answer.
	 *
	 * @param questionId the question ID of this test answer
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the act ID of this test answer.
	 *
	 * @return the act ID of this test answer
	 */
	public long getActId();

	/**
	 * Sets the act ID of this test answer.
	 *
	 * @param actId the act ID of this test answer
	 */
	public void setActId(long actId);

	/**
	 * Returns the precedence of this test answer.
	 *
	 * @return the precedence of this test answer
	 */
	public long getPrecedence();

	/**
	 * Sets the precedence of this test answer.
	 *
	 * @param precedence the precedence of this test answer
	 */
	public void setPrecedence(long precedence);

	/**
	 * Returns the answer of this test answer.
	 *
	 * @return the answer of this test answer
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this test answer.
	 *
	 * @param answer the answer of this test answer
	 */
	public void setAnswer(String answer);

	/**
	 * Returns the is correct of this test answer.
	 *
	 * @return the is correct of this test answer
	 */
	public boolean getIsCorrect();

	/**
	 * Returns <code>true</code> if this test answer is is correct.
	 *
	 * @return <code>true</code> if this test answer is is correct; <code>false</code> otherwise
	 */
	public boolean isIsCorrect();

	/**
	 * Sets whether this test answer is is correct.
	 *
	 * @param isCorrect the is correct of this test answer
	 */
	public void setIsCorrect(boolean isCorrect);

	/**
	 * Returns the feedback correct of this test answer.
	 *
	 * @return the feedback correct of this test answer
	 */
	@AutoEscape
	public String getFeedbackCorrect();

	/**
	 * Sets the feedback correct of this test answer.
	 *
	 * @param feedbackCorrect the feedback correct of this test answer
	 */
	public void setFeedbackCorrect(String feedbackCorrect);

	/**
	 * Returns the feedbacknocorrect of this test answer.
	 *
	 * @return the feedbacknocorrect of this test answer
	 */
	@AutoEscape
	public String getFeedbacknocorrect();

	/**
	 * Sets the feedbacknocorrect of this test answer.
	 *
	 * @param feedbacknocorrect the feedbacknocorrect of this test answer
	 */
	public void setFeedbacknocorrect(String feedbacknocorrect);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TestAnswer testAnswer);

	public int hashCode();

	public CacheModel<TestAnswer> toCacheModel();

	public TestAnswer toEscapedModel();

	public String toString();

	public String toXmlString();
}